export const ADD_COMMENT = "BLOG/OPEN_POST/ADD_COMMENT";
export const RETRIEVE_POST = "BLOG/OPEN_POST/RETRIEVE_POST";
export const EDIT_OPEN_POST = "BLOG/OPEN_POST/EDIT_OPEN_POST";

export const FETCH_POSTS = "BLOG/POST/FETCH_POSTS";
export const ADD_POST = "BLOG/POST/ADD_POST";
export const EDIT_POST = "BLOG/POST/EDIT_POST";
export const DELETE_POST = "BLOG/POST/DELETE_POST";
